### ISSUE TITLE
Support for Scala 2.13

### ISSUE THREAD

**Issue by iamsmkr** [StackVista/akka-http-pac4j#32]
When could we expect support for Scala 2.13

**Comment by giiita** [comment]
Can we expect ongoing maintenance in the future, maintainers?

**Comment by hierynomus** [comment]
Yes, Once PR #36 is approved, Scala 2.13 support will be in. Sorry for not responding sooner.

**Comment by owler** [comment]
no Scala 2.13 support so far?

**Comment by ptrdom** [comment]
Just released `v0.8.1` for 2.12/2.13.
